import Head from 'next/head'
import Button from './components/button'
import React, { useState } from "react"
import TextBox from './components/textBox'
import Link from 'next/link'
import Navbar from './navBar'

export default function Home() {
  const [ screen, setScreen ] = useState(0) // 0 is Main Screen, 1 is Create Account, 2 is Sign In
  
  return (
    <>
    <div className = "headers">
      <Head>
        <title>Training Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </div>


    </>
  )
}
